ChangeLog
Config/config_timeseries.xml
Tools/copy_html
atm_diag/plot_surfaces_cons.ncl
averager/Makefile
cesm_utils/cesm_utils/create_postprocess
diagnostics/diagnostics/atm/Config/config_diags_atm.xml
diagnostics/diagnostics/atm/atm_avg_generator.py
diagnostics/diagnostics/lnd/lnd_avg_generator.py
diagnostics/diagnostics/ocn/Config/config_diags_ocn.xml
diagnostics/diagnostics/ocn/Plots/cpllog_timeseries.py
diagnostics/diagnostics/ocn/Plots/moc_annual_timeseries.py
diagnostics/diagnostics/ocn/Plots/moc_monthly_timeseries.py
diagnostics/diagnostics/ocn/Plots/poplog_timeseries.py
diagnostics/diagnostics/ocn/Plots/regional_mean_timeseries.py
diagnostics/diagnostics/ocn/ocn_avg_generator.py
mpi_utils/Makefile
reshaper/Makefile
timeseries/timeseries/cesm_tseries_generator.py

Bug fixes including timeseries generation and copy_html.
Tested with the latest CIME tag and st_archive location of files
which resulted in changing the path location of ocn log and cpl log
files in config_diags_ocn.xml. Postprocessing of older datasets
will need to be aware of these path changes for ocean timeseries
plots to work correctly.
Test suite: 5 years of test.f09_g16.BC5L45BGC data
Fixes [Github issue #]: These bug-fixes weren't in the github issues but
rather reported directly to me via email.
User interface changes: config_ocn_diags.xml -
<entry id="OCNDIAG_CPLLOGFILEPATH" value="$DOUT_S_ROOT/logs" />
<entry id="OCNDIAG_OCNLOGFILEPATH" value="$DOUT_S_ROOT/logs" />
Input data changes: none
Code review:

bug-fix and code clean-up

---

Config/config_postprocess.xml
Machines/machine_postprocess.xml
Templates/env_diags.tmpl
Templates/env_postprocess.tmpl
cesm_utils/cesm_utils/create_postprocess
diagnostics/diagnostics/ice/Config/config_diags_ice.xml
diagnostics/diagnostics/ice/ice_avg_generator.py
diagnostics/diagnostics/ice/ice_diags_bc.py
diagnostics/diagnostics/lnd/Config/config_diags_lnd.xml
diagnostics/diagnostics/lnd/lnd_avg_generator.py

- bug fix for ice diags_bc.py "ice_vol*" symlink
- add valid_values to env_*.xml description comment
- change all postprocessing default queues to geyser in preparation
for CMIP6 runs where allocation on YS will be needed for the runs.
Test suite: for ice diags tested with SO2_feedbackrun1_2020-2100_serial.001
Fixes [Github issue #]: Issue #39 for ice not able to reproduce problem for land
User interface changes: None
Input data changes: None
Code review:

- update ice and lnd avg generator to allow netcdf_format XML input

---

atm_diag/tables_chem.ncl
atm_diag/tables_soa.ncl

Simone's mods to atm_diags for tables_chem.ncl and tables_soa.ncl
These NCL mods have not been tested on any data sets accessible 
from the postprocessing suite on yellowstone. They will be tested on 
cheyenne for the ASD projects once the postprocessing suite is 
installed on cheyenne.

updates for CAM-Chem from Simone

---

Config/config_postprocess.xml
Machines/cheyenne_modules
Machines/machine_postprocess.xml
Templates/batch_cheyenne.tmpl
cesm_utils/cesm_utils/create_f2py_remap
create_python_env
examples/ASD-Cheyenne-DP/env_postprocess.xml
examples/ASD-Cheyenne-DP/env_timeseries.xml
examples/ASD-Cheyenne-DP/timeseries
ocn_diag/tool_lib/zon_avg/makefile
timeseries/timeseries/cesm_tseries_generator.py

NOTE - only the timeseries generation and the atm_averages has been successfully
tested with the PR. Code is needed for ASD projects and cylc interaction.

updates for cheyenne port

---

Machines/cheyenne_modules
Machines/machine_postprocess.xml
Machines/machine_postprocess.xsd
Templates/batch_cheyenne.tmpl
cesm_utils/cesm_utils/cesmEnvLib.py
cesm_utils/cesm_utils/create_f2py_remap
cesm_utils/cesm_utils/create_postprocess

XML updates for PE counts on Cheyenne
and fix for f2py compile on Cheyenne

update for pe counts on cheyenne

---

diagnostics/diagnostics/atm/atm_diags_bc.py
diagnostics/diagnostics/atm/model_vs_model.py
diagnostics/diagnostics/atm/model_vs_obs.py

Fix to atm diags cset1 tables not being moved correctly to the cset1 subdir.

update to make sure cset1 tables get moved correctly

---

ocn_diag/tool_lib/zon_avg/makefile

accidentally removed the makefile for ocean diag zonal average tool

add back in ocn za makefile

---

Machines/machine_postprocess.xml

The small queue on cheyenne is not yet working so switched postprocessing
tasks back to using the regular queue for all cheyenne jobs.

update the machine_postprocess.xml for cheyenne

---

Tools/link_history_files.py
diagnostics/diagnostics/ocn/Plots/surface_flux_fields.py
ocn_diag/ncl_lib/sfcflx.ncl
ocn_diag/ncl_lib/sfcflx_za.ncl
ocn_diag/ncl_lib/sfcflx_za_diff.ncl

bug fixes related to issue #91. Tested with	b.e20.BHIST.f09_g17.20thC.195_01
and	b.e20.BHIST.f09_g17.20thC.192_01 years 1960-1969. Plots are located here:
http://www.cesm.ucar.edu/models/cesm2.0/model_diagnostics/test/b.e20.BHIST.f09_g17.20thC.195_01/

bug fix to surface flux plots for ocean diagnostics

---

diagnostics/diagnostics/ocn/Plots/surface_flux_fields.py
ocn_diag/ncl_lib/sfcflx_za.ncl

fixed problem with html linking to the correct plot names.
Fixes more with issue #91.
Tested with same data sets as PR #103.

minor fix in html for PR #103

---

diagnostics/diagnostics/ice/Config/config_diags_ice.xml
diagnostics/diagnostics/ice/Plots/__init__.py
diagnostics/diagnostics/ice/Plots/ice_diags_plot_factory.py
diagnostics/diagnostics/ice/Plots/web_hem_avg_wLENS.py
diagnostics/diagnostics/ice/Plots/web_hem_avg_wLENSDiff.py
ice_diag/ChangeLog
ice_diag/code/web_hem_avg.ncl
ice_diag/code/web_hem_avg_wLENS.ncl
ice_diag/web/timeseries.html
ice_diag/web/timeseries_diff.html

Added sea ice diagnostics comparing simulations with LENS spread for 20th century simulations. Changes are to add ncl plotting script, XML flags to call these plots and associated python scripts, and html of output plots.
This has been tested on yellowstone.

CICE lens spread

---

Machines/machine_postprocess.xml
cesm_utils/cesm_utils/create_postprocess
diagnostics/diagnostics/imb/Config/config_diags_iomb.xml
diagnostics/diagnostics/imb/Config/iomb-sample.cfg

First pass at generating IOMB runs from the ILAMB infrastructure.
Successfully creates iomb_initialize and iomb_diagnostics scripts.

IOMB integration

---

ocn_diag/ncl_lib/cpl6_log_timeseries_fw.ncl
ocn_diag/ncl_lib/cpl7b_log_timeseries_fw.ncl

I did test these changes and they produce the expected results.
http://webext.cgd.ucar.edu/B1850/b.e20.B1850.f09_g17.pi_control.all.265/ocn/diag_work.115-139/MODEL_TIMESERIES/cplfwbudget.png

Fix units in FW plots.

---

lnd_diag/inputFiles/set1_clm.txt
lnd_diag/inputFiles/set2_clm.txt
lnd_diag/inputFiles/set5_clm.txt
lnd_diag/inputFiles/variable_master4.3.ncl
lnd_diag/shared/lnd_func.ncl
lnd_diag/shared/variable_master4.3.ncl

Added coupler energy balance diagnostics to sets 1, 2, and 5.
Tested on cheyenne and geyser:
http://webext.cgd.ucar.edu/B1850/b.e20.B1850.f09_g17.pi_control.all.279/lnd/b.e20.B1850.f09_g17.pi_control.all.279.5_19-b.e20.B1850.f09_g17.pi_control.all.266.5_19/setsIndex.html

Add CPL_ENERGY_BAL diagnostics

---

conform/conform/cesm_conform_generator.py
conform/conform/cesm_extras

Includes several changes, but most modify the pyconform input json
files to include the correct time-invariarant variables for the
final output files to be cf compliant.

Changes needed to get more definitions working with PyConform

---

lnd_diag/inputFiles/set10_clm.txt
lnd_diag/inputFiles/set11_clm.txt
lnd_diag/model-obs/set_11.ncl
lnd_diag/model1-model2/set_11.ncl

Minor modifications to lnd_diags for Greenland ice sheet plot sets 10 and 11.

updates to lnd diags sets 10 and 11 on behalf of @lenae101

---

Templates/batch_cheyenne.tmpl
atm_diag/plot_vertical_zonal_mean_chem.ncl
atm_diag/plot_vertical_zonal_mean_chem_perc.ncl
atm_diag/profiles_aircraft_noaa.ncl
atm_diag/tables_soa.ncl
diagnostics/diagnostics/atm/atm_avg_generator.py

These bug fixes will need to be tested in conjunction with upcoming updates to the list of
variables included in the atm_avg_generator.py for AMWG chemistry diags.

bug fixes for @tilmes issue #146

---

lnd_diag/inputFiles/set2_cn.txt
lnd_diag/inputFiles/variable_master4.3.ncl
lnd_diag/model1-model2/set_2.ncl
lnd_diag/shared/variable_master4.3.ncl

Add grain carbon variables (3) to set2.
Tested on cheyenne and geyser.
Test case directory:
/glade/p/work/oleson/diagnostics/runs/b.e20.BHIST.f09_g17.20thC.297_02
Test case output:
http://webext.cgd.ucar.edu/B20TH/b.e20.BHIST.f09_g17.20thC.297_02/lnd/b.e20.BHIST.f09_g17.20thC.297_02.1996_2005-b.e20.BHIST.f09_g17.20thC.297_01.1996_2005/setsIndex.html

Add grain carbon variables to set2

---

Config/config_conform.xml
Config/config_timeseries.xml
conform/conform/cesm_conform_generator.py
conform/conform/cesm_conform_initialize.py
timeseries/timeseries/cesm_tseries_generator.py

Modifications to conform portion to create more variables
Modifications to the timeseries default streams
Remove some variables from the land time series files

Misc. Changes

---

conform/conform/cesm_conform_generator.py
conform/conform/cesm_extras

Changes needed to work with CMIP6 data request 01.00.25
They renamed ocnBgChem to ocnBgchem in the request which required some minor modifications.
Added code to handle the dimensions landuse and iceband
This PR contains the removal of some print statements.

Conform updates

---

conform/conform/cesm_conform_generator.py
conform/conform/cesm_extras
timeseries/timeseries/chunking.py

Also includes the requested timing information for pyconform

Changes needed to get more definitions working

---

timeseries/timeseries/chunking.py

fixe issue #173.
Tested with 10 years of CESM2.0 B1850 data and 8 different component data streams. 
Completed in Total Time: 1642.32731199 seconds. Used sbatch settings:
```
#PBS -l select=4:ncpus=18:mpiprocs=18
#PBS -l walltime=00:30:00
```
NOTE: this test excluded the "mapping" variable in the CISM env_timeseries.xml specification due
to a problem in netCDF4-python and masked arrays. See [https://github.com/Unidata/netcdf4-python/pull/852] (https://github.com/Unidata/netcdf4-python/pull/852 ) for details. 
Tested with 2 years of LENS data (CESM 1.2 based tag) and 7 component data streams. 
Completed in Total Time: 1442.16037607 seconds. Used sbatch settings:
```
#PBS -l select=1:ncpus=24:mpiprocs=24
#PBS -l walltime=00:30:00
```

timeseries chunking fix 

---

Config/config_timeseries.xml
Machines/machine_postprocess.xml
conform/conform/cesm_conform_generator.py
conform/conform/cesm_extras
timeseries/timeseries/cesm_tseries_generator.py

- Set new tseries chunking sizes
- Change default proc counts for cheyenne for tseries, xconform, and ice and ocean averages
- Changes needed to get more defs to work for pyconform
- Change the tseries subcommunicator size to get better throughout for cmip

Modifications for CMIP6 runs

---

lnd_diag/inputFiles/set1_c13.txt
lnd_diag/inputFiles/set1_cn.txt
lnd_diag/inputFiles/set2_c13.txt
lnd_diag/inputFiles/set2_cn.txt
lnd_diag/inputFiles/set5_c13.txt
lnd_diag/inputFiles/set5_cn.txt
lnd_diag/inputFiles/set6_cnFlx.txt
lnd_diag/inputFiles/variable_master4.3.ncl
lnd_diag/model-obs/set_1.ncl
lnd_diag/model-obs/set_10.ncl
lnd_diag/model-obs/set_11.ncl
lnd_diag/model-obs/set_2.ncl
lnd_diag/model-obs/set_5.ncl
lnd_diag/model-obs/set_6.ncl
lnd_diag/model1-model2/set_1.ncl
lnd_diag/model1-model2/set_10.ncl
lnd_diag/model1-model2/set_11.ncl
lnd_diag/model1-model2/set_1AnomPlot.ncl
lnd_diag/model1-model2/set_1DiffPlot.ncl
lnd_diag/model1-model2/set_2.ncl
lnd_diag/model1-model2/set_5.ncl
lnd_diag/model1-model2/set_6.ncl
lnd_diag/model1-model2/set_9.ncl
lnd_diag/shared/lnd_func.ncl
lnd_diag/shared/variable_master4.3.ncl

Add new derived variable NUPTAKE_FRACTION
Handle C14 variables properly
Fix C13, C14 units
Revise C13, C14 calculations
Remove K to C conversion for set9
Add C13_NBP, C14_NBP
Tested here:
http://webext.cgd.ucar.edu/B1850/b.e21.B1850.f09_g17.PMIP4-127ka.001/lnd/b.e21.B1850.f09_g17.PMIP4-127ka.001.601_700-b.e21.B1850.f09_g17.CMIP6-piControl.001.1101_1200/setsIndex.html

Add NPUTAKE_FRACTION, fix C13,C14 units, revise C13,C14 calculation

---

Tools/ration_script
timeseries/template.timeseries
timeseries/timeseries/cesm_tseries_generator.py

I will be creating templates for various postprocessing steps which are better integrated with cime.
The original files are still in place and so current functionality is not adversely affected.

better integration with cime

---

Config/config_timeseries.xml
Machines/aleph_modules
Machines/machine_postprocess.xml
Templates/batch_aleph.tmpl
Templates/cylc_batch_aleph.tmpl
Tools/ration_script.aleph
cesm_utils/cesm_utils/create_postprocess
create_python_env
timeseries/template.timeseries
timeseries/template.timeseries_transfer
timeseries/timeseries/cesm_tseries_generator.py
timeseries/timeseries/chunking.py

Port to aleph plus a bug fix in chunking.py - variables calendar and units are not defined if size<=1

Aleph port

---

diagnostics/diagnostics/ice/ice_avg_generator.py
diagnostics/diagnostics/ocn/ocn_diags_generator.py

Fixes some issues in ocn_diags_generator.py where has_keys is not available in Python 3.

Fix has_key logic for Python 3
