NCAR/CESM_postprocessing

Machines/machine_postprocess.xml, Machines/machine_postprocess.xsd, cesm_utils/cesm_utils/create_postprocess
The PROJECT code variable had been set in the machine_postprocess.xml but
this doesn't work in a shared install of the virtualenv. So, moved the project
setting to be a command line option to create_postprocess as:
create_postprocess --caseroot [path-to-caseroot] {--project [project-code] 
--cesmtag [cesm-release-tag] --debug [level] --backtrace}
=> move PROJECT from XML to an optional argument to create_postprocess.

Config/config_postprocess.xml, Machines/machine_postprocess.xml, Templates/batch_cheyenne.tmpl
This PR fixes some inconsistencies that were introduced in PR #55 between
the postprocessing timeseries submission script and the cylc workflow.
It also added env var 
I_MPI_DEVICE=rdma 
to the  cheyenne submission scripts per CISL help desk ticket 145062 suggestion.
Successfully tested with timeseries generation for Simone's ASD run b.e15.B5505C5WCCML45CNR.f09_g16.control.cam5_4.002
=> fixes for cheyenne PE settings 

cesm_utils/cesm_utils/create_postprocess
There was a bug in create_postprocess for yellowstone when the 
nodes attribute was not present in the URL. Fixed and tested with:
create_postprocess --caseroot $runs/toss --project foo --cesmtag bar
=> fix for optional nodes attribute in XML elements

Machines/machine_postprocess.xml, Tools/ration_example.py, Tools/ration_script
The cf_units module was moved into the default python site_packages location on 
yellowstone at:
/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/site-packages/cf_units-1.1-py2.7.egg
Updated the machines_postprocess.xml PYTHONPATH element to include this new path.
Tested using data from b.e20.B1850.f09_g16.pi_control.all.136 to generate timeseries files.
=> update for cf_units on yellowstone to be included in PYTHONPATH 

Templates/cylc_batch_cheyenne.tmpl, Templates/cylc_batch_edison.tmpl, Templates/cylc_batch_yellowstone.tmpl, Tools/pp_config, Tools/ration_script
Add command line args to pp_config to allow for the
output of batch submission information to by used by the cylc workflow scripts.
See pp_config --help in a new postprocessing caseroot for supported options.
=> update to pp_config to support query of batch info for cylc

Config/config_timeseries.xml, Tools/ration.log, atm_diag/plot_improve_scatter_pdf.ncl, atm_diag/profiles_aircraft_noaa.ncl, diagnostics/diagnostics/atm/model_vs_model.py, diagnostics/diagnostics/atm/model_vs_obs.py, diagnostics/diagnostics/ocn/Plots/zonal_average_3d_fields.py, ocn_diag/ncl_lib/field_3d_za.ncl, ocn_diag/ncl_lib/field_3d_za_diff.ncl, timeseries/timeseries/cesm_tseries_generator.py, timeseries/timeseries/chunking.py
- Fix CISM timeseries generation using a couple of wrapper methods in chunking.py to get
around problems with cf_units and time attribute = "common_year since...". Tested with 
44 years of CISM data from PI Control run 136
- Fix atm diags copy of cset1 and set1 tables to the correct diagnostics subdirectories
- Fix ocn diags NCL field_3d_za.ncl and field_3d_za_diff.ncl files to only look at basin regions
indexed from 0:6 in both the model and obs files. This fixes the problem related to the removal
of the Caspian Sea as a basin region (index 14) and comparison with obs and older pop data.
=> fixes for CISM timeseries, ocn diags and atm diags

Tools/count_tseries_vars.py
- bug fix to chunking for CISM time_value floats causing a cf_units to fail with an out-of-date
- add option TIMESERIES_GENERATE_ALL to env_postprocess to override the tseries_create 
element settings in the env_timeseries.xml so that all available history slice streams are converted
to variable timeseries files. 
- set the MODEL_VS_CONTROL=FALSE as the default for env_diags_ocn.xml
Tested with default cylc suite settings from CESM-WF repo and variable timeseries generation
for the b.e20.BHIST.20thC.144_01 data output.
=> bug fixes and enhancements

Config/config_timeseries.xml, Templates/batch_cheyenne.tmpl, Templates/postprocess.tmpl, ocn_diag/tool_lib/zon_avg/makefile, timeseries/timeseries/chunking.py
add more file streams for timeseries; 
fix memory leak in chunking; 
append to ts_status.log and add datetime stamp to the end of log filenames
Test - generated variable timeseries for CISM and MOSART files from run
b.e20.BHIST.f09_g17.20thC.179_03
Fixes issues #85 and #86.
=> bug fixes for timeseries

timeseries/timeseries/cesm_tseries_generator.py
minor problem fix for parallel chunking where directory creation needed
to be done on rank 0. 
Tested with 5 years or day_5 (cam.h7) history data, 2 year chunks, 
with complete_chunk = false.
=> bug fix to parallel timeseries chunking

Machines/machine_postprocess.xml, Tools/link_history_files.py, cesm_utils/cesm_utils/create_postprocess, diagnostics/diagnostics/imb/Config/config_diags_iomb.xml, diagnostics/diagnostics/imb/Config/iomb-sample.cfg
add XML definitions to support ilamb and iomb integration on cheyenne. 
Change required because create_postprocess is failing on cheyenne without
these definitions.
=> Iomb and ilamb integration fix for cheyenne

cesm_utils/cesm_utils/create_ocn_za
create_ocn_za creates a machine dependent makefile with instructions on how to
compile the ocean zonal average tool, za. This fix removes an existing makefile,
if it exists, prior to creating the new makefile as part of create_python_env.
=> minor fix to create_ocn_za script

Machines/geyser_modules, Machines/machine_postprocess.xml, Templates/batch_geyser.tmpl
There was a problem with the ocean za tool not being able to find the libnetcdff.so.5 library
as it now requires that the za tool be compiled with gnu fortran rather than intel due
to the constraint of the gnu build of slurm. 
This PR adds a LD_LIBRARY_PATH variable to the batch_geyser.tmpl template file. 
Tested with 6 years of ocean data and the ocn_diagnostics_geyser batch submission script.
=> add LD_LIBRARY_PATH to batch_geyser.tmpl

Config/config_timeseries.xml, Machines/geyser_modules, Machines/machine_postprocess.xml, Templates/batch_cheyenne.tmpl, Templates/postprocess.tmpl
The ocn_diagnostics_geyser batch script that is created when create_postprocess is run on cheyenne needs to set the OCNDIAG_DIAGROOTPATH
XML variable to point to the geyser virtualenv (POSTPROCESS_PATH_GEYSER/ocn_diag)
rather than the default cheyenne virtualenv (POSTPROCESS_PATH/ocn_diag) because
the zonal average tool (za) is compiled differently for each machine. 
This PR also includes a fix for running IMB on cheyenne so that the libudunits is 
included in the LD_LIBRARY_PATH.
=> fix for ocn_diagnostics_geyser

cesm_utils/Makefile, conform/Makefile, diag_utils/Makefile, diagnostics/Makefile, timeseries/Makefile
Not able to repeat the problem with building the virtualenv on cheyenne and the Makefile when using the rule all: develop.
=> revert Makefile all rule to develop 

Machines/machine_postprocess.xml
**IMPORTANT NOTE** - if there are memory issues, try first running with fewer MPI tasks per node
=> update the machine PE defaults in preparation for CMIP6 

cesm_utils/cesm_utils/create_postprocess
The POSTPROCESS_PATH and POSTPROCESS_PATH_GEYSER environment variables 
both need to be set when running create_postprocess on either cheyenne or geyser. 
Note: when create_postprocess is run on geyser, the POSTPROCESS_PATH and the POSTPROCESS_PATH_GEYSER are the same. 
The distinction is important when running create_postprocess on cheyenne because the
batch submission scripts for geyser are included in a cheyenne postprocessing caseroot to
allow for submission of jobs to geyser from cheyenne.
=> minor fix to create_postprocess for geyser

lnd_diag/shared/lnd_func.ncl
Prevent set errors for CPL_ENERGY_BAL for versions of CLM other than CLM5 (CLM4 and CLM4.5).
=> Fix for CPL_ENERGY_BAL when input variables are missing (CLM4/CLM45)

timeseries/timeseries/chunking.py
problem with chunking.py and hourly clm data. This fix looks at the bounds attribute of a variable to determine the correct time step sequence.  Tested with clm day_1, hour_1, hour_3, hour_6, min_30 and  month_1;  mosart month_1; and cism year_1 data streams.
=> fix for Issue #138

Machines/machine_postprocess.xml
fix compile issue with f2py and intel for both geyser and cheyenne; 
use the command 
`f2py -c --help-fcompiler `
to see the list of fortran compilers supported by f2py
=> minor update to fy2py compilation settings to use intel

timeseries/timeseries/chunking.py
The chunking.py code had commented out the code to get the time_period_freq netcdf global
attribute from the first history slice file for a given output stream. This was to allow for older
datasets that did not have this attribute. @sherimickelson - is this commented out code an artifact from some of your testing?
Tested with ocean BGC data where the pop.h stream was set to annual means output rather than
the default monthly means.
=> uncomment the time_period_freq get global attribute

Tools/pp_config
the processXmlLib.xml_to_dict method needs to be flushed out correctly to recursively resolve
nested variables. Substituting this call with cesmEnvLib.readXML.
=> recursively resolve all XML variables in the env_dict

diagnostics/diagnostics/ocn/ocn_avg_generator.py
The pyAverager was calculating the monthly SALT, TEMP and MOC variables for the monthly moc 
file unnecessarily because the NCL only requires the MOC variable. This change ensures that the
mocm file doesn't become unnecessarily large.
=> remove SALT and TEMP from ocn diags timeseries mocm climo file

ocn_diag/ncl_lib/U_eq.ncl, ocn_diag/ncl_lib/field_3d_za.ncl, ocn_diag/ncl_lib/iagez.ncl, ocn_diag/ncl_lib/sst_eq_pac_seasonal_cycle.ncl
Several fixes for high-resolution ocean diagnostics:
- fixes U_eq.ncl for high-res grids.
- check if iage exists before trying to create 3d za for it.
- fix sst_eq_pac_seasonal_cycle for high-res grids.
Testing: ran the tool for a high res G case:  http://webext.cgd.ucar.edu/GIAF/g.e20.G.TL319_t13.control.001/ocn/diag_work_debug.21-25/MODEL_VS_OBS/
=> Fixes for high-res ocean diagnostics

diag_utils/diag_utils/diagUtilsLib.py, lnd_diag/shared/se2fv_esmf.regrid2file.ncl
Add CLM regridding support for SE_NE120 to FV_192x288 (the only option previously was regridding to FV_768x1152).
Tested using postprocessing case:
/gpfs/fs1/work/oleson/diagnostics/runs/Branch.E.13B1850C5CN.ne120_t12.02.sehires31
This is a model to model comparison in which both SE_NE120 cases were regridded to FV_192x288.
Diagnostics output is here:
http://webext.cgd.ucar.edu/B20TH/Branch.E.13B1850C5CN.ne120_t12.02.sehires31/lnd/Branch.E.13B1850C5CN.ne120_t12.02.sehires31.10_14-B.E.13B1850C5.ne120_t12.03.sehires31.10_14/setsIndex.html
=> Add CLM regridding support for SE_NE120 to FV_192x288

Machines/cheyenne_modules, Machines/dav_modules, timeseries/timeseries/chunking.py
fix issue #175 with MaskedArrays and character variable arrays in CISM history data and timeseries chunking. Tested with 10 years of fully coupled timeseries data on both cheyenne and DAV. 
Requires a rebuild of virtualenv and new ncar_pylib clones:
Cheyenne - 20181024
DAV - 20181029
=> update for netCDF4-python v1.4.2 added to ncar_pylib 

lnd_diag/model-obs/set_7.ncl, lnd_diag/model1-model2/set_7.ncl
MOSART history files now have double-precision variables while set_7.ncl assumes single-precision variables.  These are changes to allow for double-precision while maintaining backwards compatibility for single-precision MOSART variables.
A test case directory is here:
/gpfs/fs1/work/oleson/diagnostics/runs/b.e20.B1850.f19_g17.release_cesm2_1_0.002
Output is here:
http://webext.cgd.ucar.edu/B1850/b.e20.B1850.f19_g17.release_cesm2_1_0.002/lnd/b.e20.B1850.f19_g17.release_cesm2_1_0.002.51_180-b.e21.B1850.f09_g17.CMIP6-piControl.001.771_900/setsIndex.html
=> Set 7 changes to account for new double-precision mosart history files

diag_utils/diag_utils/diagUtilsLib.py, diagnostics/diagnostics/atm/atm_avg_generator.py, diagnostics/requirements.txt
remove trailing "/" from XML variables ATMDIAG_test_path_history_subdir and ATMDIAG_cntl_path_history_subdir which cause problem when globbing single variable timeseries files for the pyAverager.
Tested manually using pp caseroot:
`/gpfs/fs1/work/aliceb/sandboxes/runs/f.e13.FAMIPC5CN.ne30_ne30.beta06.t2`
Fixes github issue #200 
Also updated jinja2 dependency requirement to >= 2.10 due to github alert. Emailed CISL to request an update of the ncar_pylib virtualenv build for python2.7.x.
=> add check for trailing "/" in XML variables

Machines/dav_modules, Machines/machine_postprocess.xml, Tools/ration_script_dav
fixes issue with out-of-date versions of modules and ncar_pylib.  
Test: ration_script_dav and creaate_postprocess
Note: ilamb for python 2.7 requires that the setup.py be modified with:
'sympy==0.7.6',
=> update DAV modules and ncar_pylib version
